### ISSUE TITLE
Windows11现在似乎会阻止本地加载密码

### ISSUE THREAD

**Issue by Wrandz** [kanadeblisst00/rdp_helper#1]
如题，Windows11现在似乎会阻止本地加载密码，双击rdp文件会提示“凭据不工作”，如下图所示
![Snipaste_2023-12-06_20-31-26](https://github.com/kanadeblisst00/rdp_helper/assets/70056470/1a0ede60-d784-42b0-a269-d27ff46c4e83)
请问对此问题，有什么好的解决办法吗？

**Comment by kanadeblisst00** [comment]
你这个是因为用户名或密码错误吧，我用的系统就是最新的Windows11，没有出现这种问题

**Comment by Wrandz** [comment]
> 你这个是因为用户名或密码错误吧，我用的系统就是最新的Windows11，没有出现这种问题

明白了！感谢。我发现之所以出现这个问题，是因为我把生成的rdp文件换了电脑使用。密码似乎与电脑是绑定的。

**Comment by kanadeblisst00** [comment]
对的，计算出的密码与电脑上的某些东西绑定了，换了就不能用

**Comment by Wrandz** [comment]
> 对的，计算出的密码与电脑上的某些东西绑定了，换了就不能用

仅仅是一种可能，请教一下，这一功能是否可以在macos或者移动设备例如iphone/ipad/android上运行？
查询了一下，aardio语言只运行在Windows上。
但其实，有很多，包括我，会经常用macos连接win的远程桌面，抑或是移动设备例如ios/android平板连接。
是否也有这种可能，做一套适用于这些平台的软件？

**Comment by kanadeblisst00** [comment]
rdp文件好像是Windows专用的，其他平台都有连接rdp的软件，应该也用不到吧

**Comment by Wrandz** [comment]
> rdp文件好像是Windows专用的，其他平台都有连接rdp的软件，应该也用不到吧

你好，刚才看了一下，macOS的远程桌面app也可以支持rdp文件了。有的时候远程桌面机器很多，要变动的时候，如果是要在这些app里面操作，需要一个一个修改，或者一个一个添加，很麻烦。还是rdp文件批量生产，管理，都很方便。期盼这款软件能被移植到macos上。

**Comment by kanadeblisst00** [comment]
> > rdp文件好像是Windows专用的，其他平台都有连接rdp的软件，应该也用不到吧
> 
> 你好，刚才看了一下，macOS的远程桌面app也可以支持rdp文件了。有的时候远程桌面机器很多，要变动的时候，如果是要在这些app里面操作，需要一个一个修改，或者一个一个添加，很麻烦。还是rdp文件批量生产，管理，都很方便。期盼这款软件能被移植到macos上。

首先我得有一台mac，才能做到。等我有钱了，一定买一台再移植
